version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: siaci-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-siaci}
      POSTGRES_USER: ${POSTGRES_USER:-siaci}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-siaci_pass}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: siaci-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@siaci.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  pgdata:
